Messages and model update
KipaLogix/SporTogether pull request #8
Opened 2024-04-18 14:39 UTC by florinacho337

- updated model
- created message routes
- created message controller

2024-04-18 16:59 UTC, Bacter16 requested changes
Where message for message table? :))

2024-04-18 17:01 UTC, Domynis requested changes
e ok dar astea 2 chestii trb rezolvate

2024-04-18 17:01 UTC, Domynis commented on back_end/src/controllers/MessageController.js
> +                userId,
de pus senderId ca si in schema

2024-04-18 17:29 UTC, florinacho337 commented on back_end/prisma/schema.prisma
> +  sender    User     @relation("SentMessages", fields: [senderId], references: [id])
deci la un moment aveam textul la mesaj, dar nu stiu unde a disparut :))

2024-04-18 18:33 UTC, Bacter16 approved these changes

2024-04-21 06:58 UTC, Tiberiw approved these changes

2024-04-21 08:28 UTC, merged